// src/lib/Auth.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { auth } from './firebase'; // Import the auth object
  import { createUserWithEmailAndPassword, signInWithEmailAndPassword } from 'firebase/auth';

  let isLoginMode = true;
  let email = '';
  let password = '';
  let errorMessage: string | null = null;
  let successMessage: string | null = null;

  function toggleMode() {
    isLoginMode = !isLoginMode;
    errorMessage = null; // Clear messages on mode switch
    successMessage = null;
  }

  async function handleAuth() {
    errorMessage = null;
    successMessage = null;

    try {
      if (isLoginMode) {
        await signInWithEmailAndPassword(auth, email, password);
        successMessage = 'Login successful!';
        console.log('Login successful!');
      } else {
        await createUserWithEmailAndPassword(auth, email, password);
        successMessage = 'Registration successful! You are now logged in.';
        console.log('Registration successful!');
      } 
    } catch (error: any) {
      errorMessage = error.message;
      console.error('Authentication error:', error.message);
    }
  }

  onMount(() => {
    // Bootstrap JavaScript components might need initialization if used,
    // but for basic forms, CSS classes are often enough.
  });
</script>

<div class="container d-flex justify-content-center align-items-center min-vh-100 bg-light">
  <div class="card p-4 shadow-sm" style="width: 100%; max-width: 400px;">
    <h2 class="card-title text-center mb-4">{isLoginMode ? 'Login' : 'Register'}</h2>
    <form on:submit|preventDefault={handleAuth}>
      {#if errorMessage}
        <div class="alert alert-danger" role="alert">
          {errorMessage}
        </div>
      {/if}
      {#if successMessage}
        <div class="alert alert-success" role="alert">
          {successMessage}
        </div>
      {/if}

      <div class="mb-3">
        <label for="emailInput" class="form-label">Email address</label>
        <input
          type="email"
          class="form-control"
          id="emailInput"
          bind:value={email}
          required
        />
      </div>
      <div class="mb-3">
        <label for="passwordInput" class="form-label">Password</label>
        <input
          type="password"
          class="form-control"
          id="passwordInput"
          bind:value={password}
          required
        />
        </div>
      <button type="submit" class="btn btn-primary w-100 mb-2">
        {isLoginMode ? 'Login' : 'Register'}
      </button>
      <button type="button" class="btn btn-outline-secondary w-100" on:click={toggleMode}>
        {isLoginMode ? 'Need an account? Register' : 'Already have an account? Login'}
      </button>
    </form>
  </div>
</div>

<style>
  /* No specific styles needed here as Bootstrap handles most of it */
</style>

// personal-finance-app/src/components/Auth.jsx
import React, { useState } from 'react';
import { createUserWithEmailAndPassword, signInWithEmailAndPassword } from 'firebase/auth';
import { auth } from '../firebase';
import { TextField, Button, Box, Typography, Paper } from '@mui/material';

function Auth({ showSnackbar }) {
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [isRegistering, setIsRegistering] = useState(false);
  const [error, setError] = useState(null);

  const handleSubmit = async (e) => {
    e.preventDefault();
    setError(null);
    try {
      if (isRegistering) {
        await createUserWithEmailAndPassword(auth, email, password);
        showSnackbar('Registration successful!', 'success');
      } else {
        await signInWithEmailAndPassword(auth, email, password);
        showSnackbar('Login successful!', 'success');
      }
    } catch (err) {
      setError(err.message);
      showSnackbar(`Authentication failed: ${err.message}`, 'error');
      console.error(err);
    }
  };


  return (
    <Paper elevation={3} sx={{ p: 3, maxWidth: 400, margin: 'auto', mt: 5 }}>
      <Typography variant="h5" component="h1" gutterBottom>
        {isRegistering ? 'Register' : 'Login'}
      </Typography>
      <form onSubmit={handleSubmit}>
        <TextField
          label="Email"
          type="email"
          fullWidth
          margin="normal"
          value={email}
          onChange={(e) => setEmail(e.target.value)}
          required
        />
        <TextField
          label="Password"
          type="password"
          fullWidth
          margin="normal"
          value={password}
          onChange={(e) => setPassword(e.target.value)}
          required
        />
        {error && (
          <Typography color="error" variant="body2" sx={{ mt: 1 }}>
            {error}
          </Typography>
        )}
        <Button
          type="submit"
          variant="contained"
          color="primary"
          fullWidth
          sx={{ mt: 2 }}
        >
          {isRegistering ? 'Register' : 'Login'}
        </Button>
      </form>
      <Button
        variant="text"
        color="secondary"
        fullWidth
        sx={{ mt: 1 }}
        onClick={() => setIsRegistering(!isRegistering)}
      >
        {isRegistering ? 'Already have an account? Login' : 'Need an account? Register'}
      </Button>
      {/* Logout button is now handled in App.jsx for global state management */}
    </Paper>
  );
}

export default Auth;
